credentials:
  usernames:
    jarvis:
      email: jarvis@gmail.com
      name: jarvis
      password: $2a$12$.eLD997v7LDL6TwARgd9O.sujEDM3Ysnb5Ot7U4Zbyv1F67HkXS9m
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
    - jarvis@gmail.com
