generate_code:
  description: |
    - Generate reliable and well-structured Python code that effectively addresses the request provided here: {instruction}.
    - Your field of expertise is: {expertise}.
    - The language of the code is: {language}.
    - Conduct a comprehensive review of the generated Python code and the accompanying explanatory text.
    - Ensure the explanatory text is clear, concise, and well-structured, formatted as markdown paragraphs.
    - Highlight the code using markdown code formatting, ensuring it is enclosed in a single code block.
    - Utilize heading level 5 for any titles in the explanatory text (##### heading level 5).
  expected_output: |
    - JSON object with two keys: "code" and "text":
      - "code" should be a string containing the generated code in {language}.
      - "text" should be a string containing the explanatory text:
  agent: developer

generate_diagram:
  description: |
    - Generate a comprehensive and detailed diagram that thoroughly addresses the instruction provided here: {instruction}.
    - Utilize your field of expertise: {expertise}, with a specific focus on: {diagram_type}.
    - If {diagram_type} is Graphviz, adhere to the DOT language structure, based on the documentation provided.
    - If {diagram_type} is pytm, ensure that the code is properly formatted and syntax is correct as a python code block.
    - Ensure the generated code complies with the requirements outlined below:
      - Ensure the diagram code is valid and executable.
      - Correct any syntax errors.
      - Use your expertise in {diagram_type} to enhance code quality.
    - Utilize heading level 5 for any titles in the explanatory text (##### heading level 5).
  expected_output: |
    - JSON object with keys: "diagram_code" and "diagram_text":
      - "diagram_code" is a code block with the generated code in the specified language, clear and organized.
      - "diagram_text" is a string with concise, relevant explanatory text in markdown format.
  agent: diagrammer
